live_config_reload = true

[shell]
# For MSYS2
program = "D:/MSYS64/msys2_shell.cmd"
args = ["-defterm", "-here", "-no-start", "-ucrt64"]

# # For Git4Windows
# program = "C:\\Program Files\\Git\\bin\\bash.exe"
# args = ["--login", "-i"]

# # For WSL
# program = "C:\\Windows\\System32\\wsl.exe"
# args = ["--cd ~"]

[window]
opacity = 0.8
startup_mode = "Maximized"
dynamic_title = false
title = "Terminal"

[font]
size = 14.0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[cursor.style]
shape = "Block"
blinking = "On"

### THEME ###

# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'

blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
