[general]
live_config_reload = true
import = [
  "catppuccin-mocha.toml"
]

[shell]
# For Git4Windows
program = "C:\\Program Files\\Git\\bin\\bash.exe"
args = ["--login", "-i"]

# # For WSL
# program = "C:\\Windows\\System32\\wsl.exe"
# args = ["--cd ~"]

[window]
opacity = 0.8
startup_mode = "Maximized"
dynamic_title = false
title = "Terminal"

[font]
size = 14.0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[cursor.style]
shape = "Block"
