require("plugin-configs.colorscheme")
require("plugin-configs.bufferline")
require("plugin-configs.nvim-tree")
require("plugin-configs.treesitter")
require("plugin-configs.coc-nvim")
require("plugin-configs.autoclose")
require("plugin-configs.telescope")
