require("plugin-configs.colorscheme")
require("plugin-configs.nvim-hardline")
require("plugin-configs.nvim-tree")
require("plugin-configs.treesitter")
require("plugin-configs.telescope")
require("plugin-configs.nvim-autopairs")
require("plugin-configs.lspconfig")
require("plugin-configs.nvim-cmp")
